
pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    sh 'docker build -t devops-app ./app'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
                // placeholder for real tests
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh 'docker-compose down && docker-compose up -d --build'
                }
            }
        }
    }
}
